baseURL = "https://mr-cade.github.io/uarc-rebuild/"
languageCode = "en-us"
title = "UARC"
theme = "ananke"
publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "Utah Amateur Radio Club"
  facebook = "https://www.facebook.com/UtahAmateurRadioClub/"
  twitter = ""
  instagram = ""
  youtube = "https://www.youtube.com/c/utahamateurradioclub"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Antenna-Farm.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]

 